services:
  - type: worker
    name: bot-gel
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: GOOGLE_CREDENTIALS_JSON
        sync: false
      - key: GOOGLE_SHEET_NAME
        value: Database-GEL-Teste
